server:
  port: 8002

spring:
  application:
    name: lexiang-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.192.101:3306/lexiang_system?serverTimezone=GMT%2B8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #wrapper处的条件可以识别 map集合不能强转
    time-zone: GMT+8
  redis:
    host: 120.27.192.101
    port: 6380

#mybatis日志
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  global-config:
    db-column-underline: true
    refresh-mapper: true #开启热加载
    configuration:
      map-underscore-to-camel-case: true #开启驼峰命名
      multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句

#Eureka配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-id-address: true
    instance-id: lexiang-system


